<%@ Page Title="Students' List" Language="C#" MasterPageFile="~/Site.Master" AutoEventWireup="true" CodeBehind="StudentList.aspx.cs" Inherits="ACMEstudentPortal.StudentList" 
    EnableEventValidation="false"%>

<asp:Content ID="Content1" ContentPlaceHolderID="MainContent" runat="server">
    <br /><br />
<asp:Label runat="server" Text="Filter by:" /> <br />
    <asp:Label runat="server" Text="Gender:" />
<asp:DropDownList runat="server" AutoPostBack="true" ID="gender">
    <asp:ListItem Text="All" value =""/>
    <asp:ListItem Text="Male" />
    <asp:ListItem Text="Female" />
 
</asp:DropDownList>


    <asp:ValidationSummary ShowModelStateErrors="true" runat="server" />
   
<asp:GridView runat="server" ID="studentsGrid"
        ItemType="ACMEstudentPortal.Models.Student" DataKeyNames="studentID" 
        SelectMethod="getStudents"
        AutoGenerateColumns="false" Width="1040px"
    UpdateMethod="updateStudent" DeleteMethod="deleteStudent"
    AutoGenerateEditButton="true" AutoGenerateDeleteButton="true" 
    AllowSorting="true" AllowPaging="true" >
        <Columns>
             <asp:DynamicField DataField="studentID" />
            <asp:DynamicField DataField="Name" />
            <asp:DynamicField DataField="Course" />
            <asp:DynamicField DataField="Nationality" />
            <asp:DynamicField DataField="Major" />
            <asp:DynamicField DataField="DateofBirth" />
            <asp:DynamicField DataField="Email" />
            <asp:DynamicField DataField="Mobile" />
            <asp:DynamicField DataField="graduationYear" />          
            <asp:TemplateField HeaderText="Sex">
              <ItemTemplate>
                <asp:RadioButtonList id="textGender" runat="server" SelectedValue = <%#: Item.sex %> >
                
                    <asp:ListItem  Text="Male" Value=Male />
                    <asp:ListItem Text="Female" Value=Female />
                    
                    </asp:RadioButtonList>
              </ItemTemplate>
            </asp:TemplateField>        
        </Columns>
    </asp:GridView>
    <asp:Button ID="exportPDF" runat="server" Text="Export To PDF" OnClick = "ExportToPDF" />
        <asp:Button ID="exportJSON" runat="server" Text="Export To JSON" OnClick = "ExportToJSON" />
    <!--
    <section>
        <div>
            <hgroup>
                <h2><%: Page.Title %></h2>
            </hgroup>
            <asp:ListView ID="studentsList" runat="server"
                DataKeyNames="studentID" GroupItemCount="10"
                ItemType="ACMEstudentPortal.Models.Student" SelectMethod="getStudents" Style="margin-bottom: 144px">
                <EmptyDataTemplate>
                    <table>
                        <tr>
                            <td>No data was returned.</td>
                        </tr>
                    </table>
                </EmptyDataTemplate>
                <EmptyItemTemplate>
                    <td />
                </EmptyItemTemplate>
                <GroupTemplate>
                    <tr id="itemPlaceholderContainer" runat="server">
                        <td id="itemPlaceholder" runat="server"></td>
                    </tr>
                </GroupTemplate>
                <ItemTemplate>
                    <td runat="server">
                        <table>
                            <tr>
                                <td>
                                    <a
                                        href="StudentDetails.aspx?studentID=<%#:Item.studentID%>">
                                       </a>
                                </td>
                            </tr>
                            <tr>
                                <td>
                                    <a
                                        href="StudentDetails.aspx?studentID=<%#:Item.studentID%>">
                                        <span>
                                            <%#:Item.name%>
                                        </span>
                                    </a>
                                    <br />
                                    <span>
                                        <b>Sex: </b><%#:Item.sex%>
                                    </span>
                                    <br />
                                </td>
                            </tr>
                            <tr>
                                <td>&nbsp;</td>
                            </tr>
                        </table>
                        </p>
                    </td>
                </ItemTemplate>
                <LayoutTemplate>
                    <table style="width: 100%;">
                        <tbody>
                            <tr>
                                <td>
                                    <table id="groupPlaceholderContainer"
                                        runat="server" style="width: 100%">
                                        <tr id="groupPlaceholder"></tr>
                                    </table>
                                </td>
                            </tr>
                            <tr>
                                <td></td>
                            </tr>
                            <tr></tr>
                        </tbody>
                    </table>
                </LayoutTemplate>
            </asp:ListView>
        </div>
    </section>
    </asp:ListView>
        </div>
    </section>
    -->
</asp:Content>
